language: python
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.2.7
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
install:
  - make
script:
  - make test
matrix:
  allow_failures:
    - python: pypy
    - python: 3.4
      env: "DJANGO_VERSION=1.4"
    - python: 3.5
      env: "DJANGO_VERSION=1.4"
    - python: 3.6
      env: "DJANGO_VERSION=1.4"
    - python: 3.7
      env: "DJANGO_VERSION=1.4"
      
    - python: 3.5
      env: "DJANGO_VERSION=1.8"
    - python: 3.6
      env: "DJANGO_VERSION=1.8"
    - python: 3.7
      env: "DJANGO_VERSION=1.8"
      
    - python: 3.5
      env: "DJANGO_VERSION=1.9"
    - python: 3.6
      env: "DJANGO_VERSION=1.9"
    - python: 3.7
      env: "DJANGO_VERSION=1.9"
